2024-05-28 15:56 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\TradingSysteam.py", line 267, in main
    if_order_map = self.DQN_engin.get_if_order_map(finally_df)
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\DQN\lib\engine.py", line 16, in get_if_order_map
    each_strategy.load_Real_time_data(
AttributeError: 'Strategy' object has no attribute 'load_Real_time_data'

2024-05-28 16:01 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\TradingSysteam.py", line 299, in main
    self.dataprovider.Binanceapp.execute_orders(
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\Major\custom.py", line 57, in wrapper
    result = func(self, client, *new_args, **new_kwargs)
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\Major\custom.py", line 471, in execute_orders
    if (float(current_size[each_symbol]) + ready_to_order_size) * symbol_map[each_symbol]['Close'].iloc[-1] < float(Response['maxNotionalValue']):
KeyError: 'KSMUSDT'

2024-05-28 16:05 ERROR Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001BD9EFD6440>
2024-05-28 16:06 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\TradingSysteam.py", line 299, in main
    self.dataprovider.Binanceapp.execute_orders(
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\Major\custom.py", line 57, in wrapper
    result = func(self, client, *new_args, **new_kwargs)
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\Major\custom.py", line 471, in execute_orders
    if (float(current_size[each_symbol]) + ready_to_order_size) * symbol_map[each_symbol]['Close'].iloc[-1] < float(Response['maxNotionalValue']):
KeyError: 'KSMUSDT'

2024-05-28 16:20 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\TradingSysteam.py", line 299, in main
    self.dataprovider.Binanceapp.execute_orders(
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\Major\custom.py", line 57, in wrapper
    result = func(self, client, *new_args, **new_kwargs)
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\Major\custom.py", line 471, in execute_orders
    if (float(current_size[each_symbol]) + ready_to_order_size) * symbol_map[each_symbol]['Close'].iloc[-1] < float(Response['maxNotionalValue']):
KeyError: 'KSMUSDT'

2024-05-28 16:23 ERROR Traceback (most recent call last):
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\TradingSysteam.py", line 299, in main
    self.dataprovider.Binanceapp.execute_orders(
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\Major\custom.py", line 57, in wrapper
    result = func(self, client, *new_args, **new_kwargs)
  File "c:\Users\user\Desktop\program\Reinforcement_learninng\finrl_achieve\project\Major\custom.py", line 471, in execute_orders
    if (float(current_size[each_symbol]) + ready_to_order_size) * symbol_map[each_symbol]['Close'].iloc[-1] < float(Response['maxNotionalValue']):
KeyError: 'KSMUSDT'

